"""
Generate requirements.txt for deploying a specific agent config.

Each agent JSON in data/agent_template/ can declare a "requirements" array
of extra pip specs it needs (e.g. the provider package for its llm/tts/stt
choices). This script merges requirements-core.txt (always required) with
that agent's own "requirements" into the requirements.txt read by pip
installs and by the deploy Dockerfile — so a deployment only installs what
the one agent it's running actually needs, and that need is declared in the
agent's own data file rather than hardcoded in code.

Usage:
    python app/galatea/build_requirements.py --config data/agent_template/Natasha.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
CORE_REQUIREMENTS_PATH = PROJECT_ROOT / "requirements-core.txt"
OUTPUT_REQUIREMENTS_PATH = PROJECT_ROOT / "requirements.txt"


def build(config_path: str | Path) -> str:
    cfg = json.loads(Path(config_path).read_text(encoding="utf-8"))
    agent_requirements = cfg.get("requirements", [])
    core_text = CORE_REQUIREMENTS_PATH.read_text(encoding="utf-8").rstrip("\n")

    lines = [
        f"# GENERATED by build_requirements.py from {config_path} — do not edit by hand.",
        "# Edit requirements-core.txt (always-required) or this agent's \"requirements\" instead.",
        "",
        core_text,
    ]
    if agent_requirements:
        lines += ["", f"# Extra packages required by {cfg.get('name', config_path)!s}:"]
        lines += list(agent_requirements)

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="Path to an agent JSON in data/agent_template/")
    args = parser.parse_args()

    output = build(args.config)
    OUTPUT_REQUIREMENTS_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT_REQUIREMENTS_PATH} for config {args.config}")


if __name__ == "__main__":
    main()
